### ISSUE TITLE
CO2e units incorrect 

### ISSUE THREAD

**Issue by adamshelley31** [Pro-Enviro/IDNI#153]
Reported By James

Check bug report (Submitted 11:57, 4th September)

In Data > Recommendations > Breakdown of Energy Costs... In the table, total carbon emissions are 1/1000th of the actual sum. It is believed that this is due to a confusion with units. For example, the screenshot shows 10,210.76 tCO2e of carbon for electricity for the company cemcor, then the total is 10.21. The total should be 10,210.76 - no dividing needed.

**Comment by mila-proenviro** [comment]
<img width="1538" alt="Screenshot 2024-10-22 at 16 20 43" src="https://github.com/user-attachments/assets/c5d42ac2-e920-4a3d-a114-0107e5aaf35e">
The numbers aren't showing or they are showing as zero

**Comment by mila-proenviro** [comment]
the issue is coming from getData() on generate-report
![image](https://github.com/user-attachments/assets/bdfd2606-f328-4119-8657-02d8f6a5885e)

**Comment by mila-proenviro** [comment]
Update: 
the issue is coming from calculateScopeTable - on line "const selectedConversionFactor"
Currecntly, the conversion factor that we are pulling is from the conversionFactors object and that's why the HH is showing as 0 
![image](https://github.com/user-attachments/assets/d110ce2b-28d5-43c3-816e-4d7c1ed024a0)

TO DO:
the conversion factor needs to be the one from the object conversionFactors[fuelType.type] or the HH data conversion factor

**Comment by mila-proenviro** [comment]
TO DO:
1. test different data 
2. check if the numbers are pulling through
3. delete console logs and comments that we dont' need

**Comment by mila-proenviro** [comment]
If statement was added to handle custom fuel type names
<img width="1520" alt="Screenshot 2024-10-23 at 12 48 50" src="https://github.com/user-attachments/assets/816184e1-adfb-4792-8a11-b6a0a87f63b1">
