### ISSUE TITLE
Add file system

### ISSUE THREAD

**Issue by SillyMonkey1925** [Pro-Enviro/IDNI#180]
Add a file system to upload and display reports

- Admin only upload
- show report
- build in pdf viewer
- show uploaded data files

**Comment by SillyMonkey1925** [comment]
@mila-proenviro 

Please make it look nice, Then upload all reports that are done. James can give you a list

@adamshelley31 Have a look at the pdf reader i used on ECP and add to this.

Thanks

**Comment by adamshelley31** [comment]
Added pdf viewer. Ready for testing, and perhaps some styling @mila-proenviro.

**Comment by mila-proenviro** [comment]
@adamshelley31 
The file list table needs to include only the files from the report section because they are pdf files. 
Maybe Capital Dev confused you, because under data there are pdf files,excel files, but we will need only the report pdfs in the table.
<img width="1528" alt="Screenshot 2024-11-11 at 11 07 16" src="https://github.com/user-attachments/assets/06517fc8-a3bd-440f-b72f-43ef3b5fd690">

**Comment by mila-proenviro** [comment]
tested on branch 180 and it is working

**Comment by mila-proenviro** [comment]
To DO:
1. create upload for files
2. this section needs to be visible only for admin and consultants

**Comment by mila-proenviro** [comment]
@adamshelley31 Adam , can you please test when you have the time - test if you can upload files, (1 file or multiple files - maximum 3), are they saving on the database to the correct company. When you upload file do you see it listed on the table? and check when you upload file if the count is changing.

**Comment by adamshelley31** [comment]
Tested, the count increases, it uploads correctly and immediately shows in the list. I can also view it without refreshing the page after upload. Nice one!
